import { ArrowRight, Check, Sparkles, FolderKanban, Star, Menu, X, Globe, AtSign, Share2, GitBranch, MessageSquare, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useState } from 'react'
import './Landing.css'
import { ProgramCards } from './ProgramsPage'

const plans = [['Basic Internship', '02 weeks', '1,999', ['Python, Flask & HTML foundations', '50-question MCQ assessment', '5 practical coding problems', 'Mentor-reviewed mini project', 'Completion certificate'], '/programs/basic'], ['Professional Internship', '04 weeks', '4,999', ['Advanced Python & PostgreSQL', 'Industry-oriented technical assessment', 'Coding challenges and feedback', 'End-to-end industry project', 'Final evaluation & certificate'], '/programs/professional'], ['Premium Internship', '06 weeks', '9,999', ['AI, LLM & prompt engineering', 'Expert assessment and analytics', 'Production-ready project experience', 'Live ARINSA product module', 'Mentor reviews & performance report'], '/programs/premium']]
const projects = [['Vertex', 'AI research workspace'], ['Morrow', 'Personal finance engine'], ['Careline', 'Care coordination system']]

export default function Landing() {
  const [open, setOpen] = useState(false)
  return <>
    <div className="announcement-bar"><strong>Discover new high-demand tracks!</strong><span>Talk to us at <a href="tel:+919123745946">+91-9123745946</a> · Available 24 hours</span></div>
    <header className="top">
      <Link className="logo brand-logo" to="/"><img src="/brand/arinsa-ai-minds-logo.png" alt="ARINSA AI MINDS" /></Link>
      <nav className={open ? 'visible' : ''}>
        <Link to="/programs" onClick={() => setOpen(false)}>Programs</Link><Link to="/curriculum" onClick={() => setOpen(false)}>Curriculum</Link><Link to="/projects" onClick={() => setOpen(false)}>Projects</Link><Link to="/about" onClick={() => setOpen(false)}>Why ARINSA</Link><Link to="/login">Sign in</Link><Link className="pill small" to="/signup">Apply now <ArrowRight /></Link>
      </nav>
      <button className="mobile" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button>
    </header>
    <main>
      <section className="v2Hero">
        <div className="v2Grid" />
        <div className="v2Copy"><div className="v2Kicker"><Sparkles /> AI INTERNSHIP PLATFORM · 2026</div><h1>Build the work<br />that begins your<br /><i>AI career.</i></h1><p>Work inside a real product studio: solve industry briefs, receive mentor review, grow your GitHub portfolio, and leave with evidence—not just a certificate.</p><div className="v2Actions"><Link to="/signup">Apply now <ArrowRight /></Link><Link to="/programs">Explore programmes</Link></div><div className="v2Trust">{['Live AI projects', 'Industry mentors', 'GitHub portfolio', 'Placement assistance'].map(x => <span key={x}><Check />{x}</span>)}</div><div className="heroStats">{[['85+', 'live AI projects'], ['1,200+', 'students trained'], ['30+', 'countries reached'], ['95%', 'completion rate']].map(x => <article key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></article>)}</div></div>
        <div className="productStage"><div className="stageTop"><b>ARINSA <em>studio</em></b><span>Professional · Week 04</span><i>AK</i></div><div className="stageBody"><aside><span>OVERVIEW</span><b>Workspace</b><b>Assignments</b><b>Projects</b><b>Feedback</b><b>Certificates</b></aside><section><div className="stageHeader"><div><small>GOOD MORNING, STUDENT</small><h2>Your work is<br />taking shape.</h2></div><div className="stageProgress"><span>PROGRAM PROGRESS</span><strong>72%</strong><i><b /></i></div></div><div className="stageProject portfolio-card"><div><FolderKanban /><span>CAREER BUILDING</span><h3>Portfolio<br />Launchpad</h3><p>Capstone workspace · Review ready</p></div><div className="goal-ring"><b>03</b><small>active goals</small></div></div><div className="stageRows"><article><GitBranch /><div><b>Portfolio update</b><small>case-study draft ready</small></div><span>Today</span></article><article><MessageSquare /><div><b>Mentor feedback</b><small>Strong structure—keep going.</small></div><span>2h ago</span></article></div></section></div></div>
      </section>
      <section className="novaStats">{[['08K', 'Students in motion'], ['126', 'Campus partners'], ['47', 'Live briefs shipped'], ['94%', 'Programme completion']].map(x => <article key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></article>)}</section>
      <section className="novaFeatures"><div className="introCopy"><small>01 / WHY ARINSA</small><h2>Not a course.<br /><i>A new standard.</i></h2></div><div className="bento">{[['Designed for real work', 'From first brief to final release, every week earns its place.'], ['A sharper circle', 'Build alongside people who raise the quality of your thinking.'], ['Proof, not promises', 'Leave with reviews, code and credentials that hold up.'], ['Room to explore', 'A focused system with enough space to make it yours.']].map((x, i) => <article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p><span>0{i + 1}</span></article>)}</div></section>
      <section className="novaJourney"><div><small>02 / THE EXPERIENCE</small><h2>A path with<br /><i>momentum.</i></h2><p>One intentional sequence from curiosity to a body of work you can put your name on.</p></div><ol>{['Choose your direction', 'Enter your studio', 'Solve real briefs', 'Build your signature project', 'Get the review', 'Carry the proof forward'].map((x, i) => <li key={x}><span>0{i + 1}</span><b>{x}</b></li>)}</ol></section>
      <section className="landing-programs"><div className="program-lead"><p>03 / PROGRAMMES</p><h1>Choose the<br/><em>right stretch.</em></h1><span>Three ways to move with intention.</span></div><ProgramCards /></section>
      <section className="novaTech"><small>04 / THE TOOLKIT</small><h2>Fluent in the<br /><i>modern stack.</i></h2><div>{['React', 'FastAPI', 'Python', 'PostgreSQL', 'Docker', 'GitHub', 'OpenAI', 'Azure', 'AWS', 'REST API', 'JWT', 'LangChain'].map(x => <span key={x}>{x}</span>)}</div></section>
      <section className="novaProjects"><small>05 / WORK THAT LANDS</small><h2>Built for the<br /><i>real world.</i></h2><div className="projectRail">{projects.map((x, i) => <article key={x[0]}><div className={'projectVisual pv' + i}><b>{x[0]}</b><i /><i /><i /></div><small>INDUSTRY BRIEF · 0{i + 1}</small><h3>{x[1]}</h3></article>)}</div></section>
      <section className="novaTestimonial"><Star fill="currentColor" /><blockquote>“I stopped saying I was learning. I had work, feedback and a point of view to show for it.”</blockquote><b>Riya Shah</b><span>Software Intern · Professional Programme</span></section>
      <section className="novaFaq"><div><small>06 / THE DETAILS</small><h2>Clear from<br /><i>the first click.</i></h2></div><div>{['How is this different from a typical internship?', 'Can I join while I am studying?', 'What can I add to my portfolio?', 'How does certificate verification work?'].map((x, i) => <details key={x}><summary><span>0{i + 1}</span>{x}<b>+</b></summary><p>Each programme is thoughtfully designed around real delivery, clear milestones and meaningful proof of progress.</p></details>)}</div></section>
      <section className="novaCta"><small>YOUR NEXT MOVE</small><h2>Build something<br /><i>people remember.</i></h2><p>Your first serious project can start here.</p><Link className="novaButton" to="/signup">Start your application <ArrowRight /></Link></section>
    </main>
    <footer className="v2Footer"><div className="footerTop"><div><Link className="logo invert" to="/"><i />arinsa <span>AI MINDS</span></Link><h2>Make your first<br /><em>serious move.</em></h2></div><form><label>FIELD NOTES FROM ARINSA</label><div><input aria-label="Email address" placeholder="Your email address" /><button aria-label="Subscribe"><ArrowRight /></button></div><small>Product thinking, career signals and studio dispatches.</small></form></div><div className="footerColumns"><div><b>PROGRAMMES</b><Link to="/programs">Foundation</Link><Link to="/programs">Professional</Link><Link to="/programs">Premium</Link></div><div><b>EXPERIENCE</b><Link to="/curriculum">Curriculum</Link><Link to="/projects">Projects</Link><Link to="/about">Mentors</Link></div><div><b>COMPANY</b><Link to="/about">About ARINSA</Link><a href="mailto:hello@arinsaaiminds.com">Contact</a><Link to="/login">Student portal</Link></div><div><b>FOLLOW</b><span className="socials"><Globe /><AtSign /><Share2 /></span><a href="#top">Back to top</a></div></div><div className="footerBottom"><span>© {new Date().getFullYear()} ARINSA AI MINDS</span><span>Built for people who build what’s next.</span></div></footer>
  </>
}
