import { CheckCircle2, ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import apiClient from '../api/client'
import Spinner from '../components/ui/Spinner'
import { hasActiveOffer, offerExpiryLabel, priceLabel } from '../utils/programOffers'
import './PlatinumDetail.css'

const why = [['Comprehensive Technical Training', 'Learn industry-relevant technologies through structured modules, practical assignments, coding exercises, and production-focused projects.'], ['Real Industry Experience', 'Gain hands-on experience by contributing to live development projects while working with experienced engineers using professional workflows and collaborative development practices.'], ['Build an Outstanding Portfolio', 'Develop multiple portfolio projects, including a production-ready capstone application that demonstrates your technical capabilities to future employers.']]
const learn = ['Advanced Python Programming', 'Backend Engineering', 'Full-Stack Web Development', 'Database Design & Optimization', 'REST API Development', 'Artificial Intelligence', 'Machine Learning', 'Deep Learning', 'Generative AI', 'Large Language Models (LLMs)', 'Prompt Engineering', 'Software Architecture', 'DevOps Fundamentals', 'Git & Collaborative Development', 'Cloud Deployment', 'Professional Software Development Lifecycle']
const receive = ['Six months of structured technical training', 'Industry internship experience', 'Production-grade project experience', 'Career mentoring', 'Technical code reviews', 'Mock interviews', 'Placement assistance', 'Detailed performance evaluation', 'Platinum Program Certificate', 'Industry Internship Certificate', 'Final Capstone Project Certificate', 'Letter of Recommendation (for outstanding performers)']
const graduate = ['Six months of practical industry experience', 'Multiple portfolio-ready software projects', 'Professional AI and software engineering skills', 'Strong interview confidence', 'Industry-recognized certifications', 'Placement assistance and career guidance', 'Opportunities to interview with ARINSA AI MINDS and participating hiring partners']
const career = ['Dedicated career mentoring', 'Resume and portfolio development', 'LinkedIn profile optimization', 'GitHub profile enhancement', 'Mock technical interviews', 'Coding interview preparation', 'HR interview guidance', 'Communication and workplace readiness', 'Performance reviews and improvement plans']

export default function PlatinumDetail(){
  const { data: programs, isLoading } = useQuery({ queryKey: ['public-programs'], queryFn: () => apiClient.get('/public/programs').then((response) => response.data) })
  if (isLoading) return <Spinner />
  const program = programs?.find((item) => item.code === 'platinum')
  const offerActive = hasActiveOffer(program)
  return <main className="platinum"><section className="platinum-hero"><div><p>24 WEEKS / 6 MONTHS · JOB GUARANTEE PROGRAM</p><h1>Platinum<br/><em>Program.</em></h1><p>Our flagship 6-month program combines comprehensive technical training, a real-world industry internship, career preparation, and placement assistance to help you launch a successful career in Software Engineering and Artificial Intelligence.</p><div className="platinum-price">{offerActive ? <><span><small>REGULAR PRICE</small>{priceLabel(program.price_inr, program.price_usd)}</span><strong><small>LIMITED-TIME OFFER</small>{priceLabel(program.offer_price_inr, program.offer_price_usd, true)}<em>{offerExpiryLabel(program)}</em></strong></> : <strong><small>PRICE</small>{priceLabel(program?.price_inr, program?.price_usd)}</strong>}</div><Link to="/signup">Apply for Platinum <ArrowRight/></Link></div><aside><b>FIRST 12 WEEKS</b><span>Technical learning & skill development</span><b>FINAL 12 WEEKS</b><span>Real industry internship</span></aside></section><section className="platinum-points">{why.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h2>{x[0]}</h2><p>{x[1]}</p></article>)}</section><section className="platinum-phases"><article><span>01</span><h2>First 12 Weeks — Technical Learning & Skill Development</h2><ul><li><CheckCircle2/>Master modern software engineering, full-stack development, cloud technologies, Artificial Intelligence, Generative AI, and Large Language Models through structured learning and practical projects.</li></ul></article><article><span>02</span><h2>Final 12 Weeks — Industry Internship</h2><ul><li><CheckCircle2/>Work alongside the ARINSA AI MINDS engineering team on real business projects, following professional development practices used in modern software companies.</li></ul></article></section><section className="platinum-extra"><article><p>CAREER DEVELOPMENT & PLACEMENT ASSISTANCE</p><h2>Prepare for your next opportunity.</h2><span>Designed to maximize your employability and prepare you for professional software engineering and AI careers.</span><ul>{career.map(x=><li key={x}><CheckCircle2/>{x}</li>)}</ul><h3>Placement Assistance</h3><span>Upon successful completion, eligible participants receive placement assistance, including opportunities to interview for suitable positions at ARINSA AI MINDS and selected hiring partners. Selection is based on technical performance, interview results, professional conduct, and availability of suitable positions.</span></article><article>{[['What you’ll learn',learn],['What you’ll receive',receive],['Graduate with',graduate]].map(([title,items])=><div key={title}><h2>{title}</h2><ul>{items.map(x=><li key={x}><CheckCircle2/>{x}</li>)}</ul></div>)}</article></section></main>}
