"""004_quiz_question_sheets

Revision ID: 3e93fc0c41a9
Revises: 7c32eed81b0a
Create Date: 2026-08-01 01:56:35.870209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e93fc0c41a9'
down_revision: Union[str, None] = '7c32eed81b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_question_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_sheet_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['quiz_question_sheets.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_sheet_assignments_sheet_student', 'quiz_sheet_assignments', ['sheet_id', 'student_id'], unique=True)
    op.add_column('quiz_questions', sa.Column('sheet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quiz_questions', 'quiz_question_sheets', ['sheet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.drop_column('quiz_questions', 'sheet_id')
    op.drop_index('ix_quiz_sheet_assignments_sheet_student', table_name='quiz_sheet_assignments')
    op.drop_table('quiz_sheet_assignments')
    op.drop_table('quiz_question_sheets')
    # ### end Alembic commands ###
