"""003_nda_and_razorpay

Revision ID: 7c32eed81b0a
Revises: d28581bb32ec
Create Date: 2026-07-30 16:23:37.461704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c32eed81b0a'
down_revision: Union[str, None] = 'd28581bb32ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nda_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('signature_name', sa.String(length=150), nullable=False),
    sa.Column('nda_version', sa.String(length=20), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['program_enrollments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('razorpay_signature', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'payments', ['razorpay_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'razorpay_signature')
    op.drop_column('payments', 'razorpay_payment_id')
    op.drop_column('payments', 'razorpay_order_id')
    op.drop_table('nda_acceptances')
    # ### end Alembic commands ###
